<?php
/** @var \CheckoutPro\OneStepCheckout\Block\Checkout $block */
?>
<?php if (!$block->isEnabled()): ?>
    <div class="message info">
        <span><?= $block->escapeHtml(__('One-Step Checkout Pro is disabled in configuration.')) ?></span>
    </div>
<?php else: ?>
    <script type="text/x-magento-init">
    {
        "#checkoutpro-one-step-checkout": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "checkoutproOneStepCheckout": {
                        "component": "CheckoutPro_OneStepCheckout/js/view/onestep-checkout",
                        "config": {
                            "checkoutConfig": <?= /* @noEscape */ $block->getSerializedCheckoutConfig() ?>
                        }
                    }
                }
            }
        }
    }
    </script>
    <div id="checkoutpro-one-step-checkout" data-bind="scope:'checkoutproOneStepCheckout'">
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>
<?php endif; ?>
